# Cactus Specific settings
# nav
nav:
  home: /
  about: /about/
  articles: /archives/
  CV: /cv/

#socials
social_links:
  github: https://github.com/ayydany
  linkedin: https://www.linkedin.com/in/ayydany
  twitter: https://twitter.com/ayyydany
  steam: https://steamcommunity.com/id/DanyBoss
  discord: https://discordapp.com/users/116873501150937097
  mail: mailto:me@ayydany.com

copyright:
  start_year: 2021